/*
 * GENERATED FILE -- DO NOT EDIT BY HAND.
 *
 * Produced by `./gradlew :tools:brandkit:generatePalette` from the two brand constants in
 * tools/brandkit/.../Brand.kt. Editing a value here will be overwritten the next time the
 * generator runs, and the contrast tests in this module will not know you meant it.
 *
 * The derivation, and the four places it deliberately departs from stock Material 3, are
 * documented in docs/DESIGN.md 2.
 */
package app.ageha.core.designsystem

import androidx.compose.ui.graphics.Color

/** One theme's worth of colour. */
internal class AgehaScheme(
	val primary: Color,
	val onPrimary: Color,
	val primaryContainer: Color,
	val onPrimaryContainer: Color,
	val inversePrimary: Color,
	val secondary: Color,
	val onSecondary: Color,
	val secondaryContainer: Color,
	val onSecondaryContainer: Color,
	val tertiary: Color,
	val onTertiary: Color,
	val tertiaryContainer: Color,
	val onTertiaryContainer: Color,
	val background: Color,
	val onBackground: Color,
	val surface: Color,
	val onSurface: Color,
	val surfaceVariant: Color,
	val onSurfaceVariant: Color,
	val surfaceTint: Color,
	val inverseSurface: Color,
	val inverseOnSurface: Color,
	val error: Color,
	val onError: Color,
	val errorContainer: Color,
	val onErrorContainer: Color,
	val outline: Color,
	val outlineVariant: Color,
	val scrim: Color,
	val surfaceBright: Color,
	val surfaceDim: Color,
	val surfaceContainer: Color,
	val surfaceContainerHigh: Color,
	val surfaceContainerHighest: Color,
	val surfaceContainerLow: Color,
	val surfaceContainerLowest: Color,
) {
	/** Every role by name, in declaration order. */
	val all: Map<String, Color> = linkedMapOf(
		"primary" to primary,
		"onPrimary" to onPrimary,
		"primaryContainer" to primaryContainer,
		"onPrimaryContainer" to onPrimaryContainer,
		"inversePrimary" to inversePrimary,
		"secondary" to secondary,
		"onSecondary" to onSecondary,
		"secondaryContainer" to secondaryContainer,
		"onSecondaryContainer" to onSecondaryContainer,
		"tertiary" to tertiary,
		"onTertiary" to onTertiary,
		"tertiaryContainer" to tertiaryContainer,
		"onTertiaryContainer" to onTertiaryContainer,
		"background" to background,
		"onBackground" to onBackground,
		"surface" to surface,
		"onSurface" to onSurface,
		"surfaceVariant" to surfaceVariant,
		"onSurfaceVariant" to onSurfaceVariant,
		"surfaceTint" to surfaceTint,
		"inverseSurface" to inverseSurface,
		"inverseOnSurface" to inverseOnSurface,
		"error" to error,
		"onError" to onError,
		"errorContainer" to errorContainer,
		"onErrorContainer" to onErrorContainer,
		"outline" to outline,
		"outlineVariant" to outlineVariant,
		"scrim" to scrim,
		"surfaceBright" to surfaceBright,
		"surfaceDim" to surfaceDim,
		"surfaceContainer" to surfaceContainer,
		"surfaceContainerHigh" to surfaceContainerHigh,
		"surfaceContainerHighest" to surfaceContainerHighest,
		"surfaceContainerLow" to surfaceContainerLow,
		"surfaceContainerLowest" to surfaceContainerLowest,
	)
}

/** Every colour Ageha uses, in every theme. No screen may define its own. */
internal object AgehaColorTokens {

	/** The light scheme. */
	val Light = AgehaScheme(
		primary = Color(0xFF4B5C92),
		onPrimary = Color(0xFFF5F1E8),
		primaryContainer = Color(0xFFDBE1FF),
		onPrimaryContainer = Color(0xFF334478),
		inversePrimary = Color(0xFFB4C5FF),
		secondary = Color(0xFF595E72),
		onSecondary = Color(0xFFF5F1E8),
		secondaryContainer = Color(0xFFDDE1F9),
		onSecondaryContainer = Color(0xFF414659),
		tertiary = Color(0xFFAF301D),
		onTertiary = Color(0xFFF5F1E8),
		tertiaryContainer = Color(0xFFFFDAD4),
		onTertiaryContainer = Color(0xFF8D1606),
		background = Color(0xFFF5F1E8),
		onBackground = Color(0xFF1C1C14),
		surface = Color(0xFFF5F1E8),
		onSurface = Color(0xFF1C1C14),
		surfaceVariant = Color(0xFFE7E3CC),
		onSurfaceVariant = Color(0xFF494737),
		surfaceTint = Color(0xFF4B5C92),
		inverseSurface = Color(0xFF323128),
		inverseOnSurface = Color(0xFFF5F1E3),
		error = Color(0xFFAF301D),
		onError = Color(0xFFF5F1E8),
		errorContainer = Color(0xFFFFDAD4),
		onErrorContainer = Color(0xFF8D1606),
		outline = Color(0xFF7A7865),
		outlineVariant = Color(0xFFCAC7B1),
		scrim = Color(0xFF000000),
		surfaceBright = Color(0xFFFDF9EC),
		surfaceDim = Color(0xFFDEDACD),
		surfaceContainer = Color(0xFFF2EEE0),
		surfaceContainerHigh = Color(0xFFECE8DB),
		surfaceContainerHighest = Color(0xFFE6E2D5),
		surfaceContainerLow = Color(0xFFF8F4E6),
		surfaceContainerLowest = Color(0xFFFDF9F0),
	)

	/** The dark scheme. */
	val Dark = AgehaScheme(
		primary = Color(0xFFB4C5FF),
		onPrimary = Color(0xFF1B2D60),
		primaryContainer = Color(0xFF334478),
		onPrimaryContainer = Color(0xFFDBE1FF),
		inversePrimary = Color(0xFF4B5C92),
		secondary = Color(0xFFC1C5DD),
		onSecondary = Color(0xFF2B3042),
		secondaryContainer = Color(0xFF414659),
		onSecondaryContainer = Color(0xFFDDE1F9),
		tertiary = Color(0xFFFFB4A6),
		onTertiary = Color(0xFF660700),
		tertiaryContainer = Color(0xFF8D1606),
		onTertiaryContainer = Color(0xFFFFDAD4),
		background = Color(0xFF1A1A1D),
		onBackground = Color(0xFFE4E2E6),
		surface = Color(0xFF1A1A1D),
		onSurface = Color(0xFFE4E2E6),
		surfaceVariant = Color(0xFF45464F),
		onSurfaceVariant = Color(0xFFC5C6D0),
		surfaceTint = Color(0xFFB4C5FF),
		inverseSurface = Color(0xFFE4E2E6),
		inverseOnSurface = Color(0xFF303034),
		error = Color(0xFFFFB4A6),
		onError = Color(0xFF660700),
		errorContainer = Color(0xFF8D1606),
		onErrorContainer = Color(0xFFFFDAD4),
		outline = Color(0xFF8F909A),
		outlineVariant = Color(0xFF45464F),
		scrim = Color(0xFF000000),
		surfaceBright = Color(0xFF39393C),
		surfaceDim = Color(0xFF131316),
		surfaceContainer = Color(0xFF1F1F23),
		surfaceContainerHigh = Color(0xFF292A2D),
		surfaceContainerHighest = Color(0xFF343438),
		surfaceContainerLow = Color(0xFF1B1B1F),
		surfaceContainerLowest = Color(0xFF0D0E11),
	)

	/** The AMOLED scheme. */
	val Amoled = AgehaScheme(
		primary = Color(0xFFB4C5FF),
		onPrimary = Color(0xFF1B2D60),
		primaryContainer = Color(0xFF334478),
		onPrimaryContainer = Color(0xFFDBE1FF),
		inversePrimary = Color(0xFF4B5C92),
		secondary = Color(0xFFC1C5DD),
		onSecondary = Color(0xFF2B3042),
		secondaryContainer = Color(0xFF414659),
		onSecondaryContainer = Color(0xFFDDE1F9),
		tertiary = Color(0xFFFFB4A6),
		onTertiary = Color(0xFF660700),
		tertiaryContainer = Color(0xFF8D1606),
		onTertiaryContainer = Color(0xFFFFDAD4),
		background = Color(0xFF000000),
		onBackground = Color(0xFFE4E2E6),
		surface = Color(0xFF000000),
		onSurface = Color(0xFFE4E2E6),
		surfaceVariant = Color(0xFF45464F),
		onSurfaceVariant = Color(0xFFC5C6D0),
		surfaceTint = Color(0xFFB4C5FF),
		inverseSurface = Color(0xFFE4E2E6),
		inverseOnSurface = Color(0xFF303034),
		error = Color(0xFFFFB4A6),
		onError = Color(0xFF660700),
		errorContainer = Color(0xFF8D1606),
		onErrorContainer = Color(0xFFFFDAD4),
		outline = Color(0xFF8F909A),
		outlineVariant = Color(0xFF45464F),
		scrim = Color(0xFF000000),
		surfaceBright = Color(0xFF39393C),
		surfaceDim = Color(0xFF000000),
		surfaceContainer = Color(0xFF17171B),
		surfaceContainerHigh = Color(0xFF1F1F23),
		surfaceContainerHighest = Color(0xFF292A2D),
		surfaceContainerLow = Color(0xFF101114),
		surfaceContainerLowest = Color(0xFF000000),
	)
}
